### ISSUE TITLE
Use UAA URL for PKS cli user creation instead of hardcoded constant

### ISSUE THREAD

**Issue by goutamtadi1** [pivotalservices/concourse-pipeline-samples#14]
Hi, 

Currently, on line https://github.com/pivotalservices/concourse-pipeline-samples/blob/master/tasks/pcf/pks/configure-pks-cli-user/task.sh#L16, the hardcoded URL  "api.((pcf_pks_domain))" is used for the PKS UAA url.  This is instead of whatever the user has entered into the tile for that value.  So the users value is ignored.

This seems like a tightly coupled dependency on using very specific URL for a given deployment. In our case, we have two PCF deployments and require PKS instances dns entries fall into same dns zone. For ex (pks-prod.a.b.c, pks-dev.a.b.c). Then we cannot use api.a.b.c for this purpose.

If this uses only uaa_url then, this would be much easier to create pks user in PKS UAA.

Thanks,
Goutam and Larry

**Comment by lsilvapvt** [comment]
Thanks for reporting the issue @goutamtadi1 . The pipeline code has been refactored in a way that accepts the PKS API endpoint as a parameter. Please let us know if you have any problems with it. 
Thanks!
https://github.com/pivotalservices/concourse-pipeline-samples/commit/d0c39e76e82e058ec6f90219bb6a3f0978a1346b

**Comment by goutamtadi1** [comment]
Thank you for taking care of that :-)
