### ISSUE TITLE
Stuck with discovering any new versions of pivnet-product : install-pks pipeline.

### ISSUE THREAD

**Issue by vaisyarajuraju123** [pivotalservices/concourse-pipeline-samples#21]
preparing build

    checking pipeline is not paused
    checking job is not paused
    discovering any new versions of pcf-pipelines-utils
    _**discovering any new versions of pivnet-product
    waiting for a suitable set of input versions**_
        pivnet-product - no versions satisfy passed constraints
    checking max-in-flight is not reached

**Comment by lsilvapvt** [comment]
Make sure that you have your pivnet token filled out correctly in the params file.
Also, please check the latest README with notes about usage of  `pks_params.yml`, for the upcoming PKS 1.1.* tile, and `pks_params_1.0.yml, which is for PKS v1.0.*.
For v1.1.*, note that at this moment, it is only available for Pivotal internal groups for tests. For you to verify if you have access, login to the Pivotal Network website, search for PKS and verify which versions are available for your user ID. If you don't see version 1.1.* in there, then, for the moment, use the params file for v1.0.*.

**Comment by lsilvapvt** [comment]
Also, check the output of the `product_release` resource in the pipeline. It can tell you if there is any error happening as it tries to get the pivnet release files.

**Comment by vaisyarajuraju123** [comment]
Thank you so much. Pivnet tokens were correct but it was stuck with PKS 1.1 which is not released to public yet. after changing to 1.0 version of PKS tile, it resolve the issue.
