### ISSUE TITLE
Deleting PKS cluster should be non-interactive

### ISSUE THREAD

**Issue by matthewmcnew** [pivotalservices/concourse-pipeline-samples#29]
When running the `delete-pks-cluster` task, deletion times out because the `--non-interactive` flag is not passed here:

https://github.com/pivotalservices/concourse-pipeline-samples/blob/a5c64bc017cfb58949932bb20fa1c3949f30ae4d/tasks/pcf/pks/delete-pks-cluster/task.sh#L8

Example output:

```
Deleting PKS cluster [cluster-name]...

Are you sure you want to delete cluster cluster-name? (y/n): Error: Unable to read confirmation input: timeout waiting for user input
you may want to use --non-interactive
```

**Comment by lsilvapvt** [comment]
PR contained the fix has bee merged.
