### ISSUE TITLE
Superficial: fix README typo

### ISSUE THREAD

**Issue by ghost** [pivotalservices/concourse-pipeline-samples#33]
<img width="905" alt="screen shot 2019-01-15 at 9 31 36 pm" src="https://user-images.githubusercontent.com/25001195/51224752-ff988b80-190c-11e9-96e3-30f1cf08f0f7.png">

Need to change to "Then unpause"

**Comment by lsilvapvt** [comment]
Thanks for reporting it. Typos fixed in all READMEs across the repository. https://github.com/pivotalservices/concourse-pipeline-samples/commit/086a239d14c2016354f367a62b509e081bcc66c4
