### ISSUE TITLE
Thank You, {{PARAMS}} Doesn't seem to work

### ISSUE THREAD

**Issue by cah-james-shingler** [pivotalservices/concourse-pipeline-samples#6]
Awesome work, .... you illustrate

  type: docker-image
  source:
    repository: 192.168.99.100:5000/ubuntu
    tag: "latest"
    insecure_registries: [ "192.168.99.100:5000" ]

Trying to do something like this

  type: docker-image
  source:
    repository: {{GRADLE_RESOURCE}}
    tag: "latest"
    insecure_registries: [ {{DOCKER_REGRISTRY}} ]

I set the pipeline with --var GRADLE_RESOURCE=192.168.1.122:5000/gradle

Get the following error: 
failed to load source-code/ci/tasks/unit.yml: yaml: invalid map key: map[interface {}]interface {}{"GRADLE_RESOURCE":interface {}(nil)}

Any Thoughts on why the Params dont work? or a work around

**Comment by lsilvapvt** [comment]
Hi Jim.
Fly's set-pipeline --var option is picky with regards to the parameter format. 
Per the Concourse FLY doc (http://concourse.ci/fly-set-pipeline.html), you may need to put double quotes around the key-value pair, e.g. --var "GRADLE_RESOURCE=192.168.1.122:5000/gradle"
If your tries do not work, last resort would be to create add that key-value pair to a params.yml file:
```
GRADLE_RESOURCE: 192.168.1.122:5000/gradle
```
 and use the option `-l params.yml` of the `fly set-pipeline` command. Good luck!
