### ISSUE TITLE
Backing up ERT is throwing this error "there was an error getting tile from registry: invalid cli flag args" and not working 

### ISSUE THREAD

**Issue by Murryy79** [pivotalservices/concourse-pipeline-samples#8]
my PCF is SAML integrated. opsman backup works with this pipeline. ERT backup failes with this error **_"there was an error getting tile from registry: invalid cli flag args"_**

root@84a414a4-9a02-4e72-5fc9-87ed844b7523:/tmp/build/dd733a1a# sh -x ./cfops_backup.sh
+ set -e
+ export LOG_LEVEL=debug
+ export no_proxy=.dfs.com
+ ops_manager_ui_user=admin
+ target_tile=elastic-runtime
+ ops_manager_ui_password=xxxxx
+ export CFOPS_ADMIN_USER=admin
+ export CFOPS_ADMIN_PASS=xxxxx
+ export CFOPS_OM_USER=ubuntu
+ export CFOPS_OM_PASS=xxxxx
+ export CFOPS_CLIENT_ID=admin
+ export CFOPS_CLIENT_SECRET=xxxxxx
+ echo TARGET TILE: elastic-runtime
TARGET TILE: elastic-runtime
+ echo OPS_MANAGER_HOSTNAME: pcfdev.dfs.com
OPS_MANAGER_HOSTNAME: pcfdev.dfs.com
+ echo FILE_REPO_IP: 1.1.0.15
FILE_REPO_IP: 1.1.0.15
+ echo FILE_REPO_SPACE:
FILE_REPO_SPACE:
+ echo FILE_REPO_PATH: /opt/app/pcf_backups
FILE_REPO_PATH: /opt/app/pcf_backups
+ date +%Y%m%d
+ export datestring=20170922
+ export build_dir=/tmp/build/dd733a1a
+ echo Current directory: /tmp/build/dd733a1a
Current directory: /tmp/build/dd733a1a
+ export backup_root_dir=/tmp/build/dd733a1a/backupdir
+ export backup_parent_dir=/tmp/build/dd733a1a/backupdir/20170922
+ export backup_file_destination=/tmp/build/dd733a1a/backupdir/20170922/elastic-runtime
+ mkdir -p /tmp/build/dd733a1a/backupdir/20170922
+ mkdir -p /tmp/build/dd733a1a/backupdir/20170922/elastic-runtime
+ chmod a+x ./cfops_linux64/cfops_linux64
+ ./cfops_linux64/cfops_linux64 list-tiles
2017/09/22 23:01:58 D0922 23:01:58.592521 346 init.go:38] not loading plugins:  open ./plugins: no such file or directory []
Available Tiles:
ops-manager
elastic-runtime
+ echo Executing cfops command...
Executing cfops command...
+ ./cfops_linux64/cfops_linux64 backup --opsmanagerhost pcfdev.dfs.com -d /tmp/build/dd733a1a/backupdir/20170922/elastic-runtime --tile elastic-runtime
2017/09/22 23:01:58 D0922 23:01:58.601938 351 init.go:38] not loading plugins:  open ./plugins: no such file or directory []
2017/09/22 23:01:58 D0922 23:01:58.602346 351 createCliCommand.go:85] checking registry for 'elastic-runtime' tile
2017/09/22 23:01:58 D0922 23:01:58.60245 351 createCliCommand.go:88] found tile in registry
2017/09/22 23:01:58 D0922 23:01:58.602623 351 createCliCommand.go:338] OpsManagerHost:  pcfdev.dfs.com
2017/09/22 23:01:58 D0922 23:01:58.602689 351 createCliCommand.go:339] AdminUser:  admin
2017/09/22 23:01:58 D0922 23:01:58.602849 351 createCliCommand.go:340] AdminPass:  xxxxxx
2017/09/22 23:01:58 D0922 23:01:58.602999 351 createCliCommand.go:341] OpsManagerUser:  ubuntu
2017/09/22 23:01:58 D0922 23:01:58.603062 351 createCliCommand.go:342] OpsManagerPass:  xxxxxx
2017/09/22 23:01:58 D0922 23:01:58.603224 351 createCliCommand.go:343] Destination:  /tmp/build/dd733a1a/backupdir/20170922/elastic-runtime
2017/09/22 23:01:58 E0922 23:01:58.603449 351 createCliCommand.go:57] there was an error getting tile from registry: invalid cli flag args
NAME:
   cfops_linux64 backup - creates a backup archive of the target tile

USAGE:
   cfops_linux64 backup [command options] [arguments...]

DESCRIPTION:
   backup --opsmanagerhost <host> --adminuser <usr> --adminpass <pass> --opsmanageruser <opsuser> --opsmanagerpass <opspass> --omr <opsmanager-encryption-password> -d <dir> --tile elastic-runtime

OPTIONS:
   --pluginargs value, -p value               Arguments for plugin to execute [$CFOPS_PLUGIN_ARGS]
   --adminpass value, --dp value              password for Ops Mgr admin (Ops Manager WebConsole Credentials) [$CFOPS_ADMIN_PASS]
   --opsmanageruser value, --omu value        username for Ops Manager VM Access (used for ssh connections) [$CFOPS_OM_USER]
   --opsmanagerpass value, --omp value        password for Ops Manager VM Access (used for ssh connections) [$CFOPS_OM_PASS]
   --clientid value, --cid value              client ID if using a UAA client instead of a UAA user [$CFOPS_CLIENT_ID]
   --tile value, -t value                     a tile you would like to run the operation on [$CFOPS_TILE]
   --nfs value                                options are 'lite' (skips optional parts of blobstore), 'full' (backs up whole blobstore) or 'bp' (only backs up buildpacks). This will only apply to elastic-runtime. Defaults to 'full' (default: "full") [$NFS_BACKUP]
   --admintoken value, --dt value             Ops Mgr OAuth admin token (not required if adminuser and adminpass are provided) [$CFOPS_ADMIN_TOKEN]
   --adminuser value, --du value              username for Ops Mgr admin (Ops Manager WebConsole Credentials) [$CFOPS_ADMIN_USER]
   --clientsecret value, --cis value          client secret if using a UAA client instead of a UAA user [$CFOPS_CLIENT_SECRET]
   --opsmanagerhost value, --omh value        hostname for Ops Manager [$CFOPS_HOST]
   --opsmanagerpassphrase value, --omr value  passphrase is used by Ops Manager 1.7 and above to decrypt the installation files during restore [$CFOPS_OM_PASSPHRASE]
   --encryptionkey value, -k value            encryption key to encrypt/decrypt your archive (key lengths supported are 16, 24, 32 for AES-128, AES-192, or AES-256) [$CFOPS_ENCRYPTION_KEY]
   --clear-bosh-manifest value                set this flag if you would like to clear the bosh-deployments.yml (this should only affect a restore of Ops-Manager) [$CFOPS_CLEAR_BOSH_MANIFEST]
   --destination value, -d value              path of the Cloud Foundry archive [$CFOPS_DEST_PATH]

root@84a414a4-9a02-4e72-5fc9-87ed844b7523:/tmp/build/dd733a1a#

**Comment by Murryy79** [comment]
anybody having similar issues with backing up ERT via cfops in SAML integrated PCF...?

**Comment by lsilvapvt** [comment]
Closing this issue as the cfops backup tool has been deprecated in favor of Bosh Backup and Restore (https://docs.cloudfoundry.org/bbr/)
