### ISSUE TITLE
Concourse pipelines with a local Docker Registry example is throwing error: invalid configuration error

### ISSUE THREAD

**Issue by caquinovs** [pivotalservices/concourse-pipeline-samples#9]
The local docker registry tutorial [https://github.com/pivotalservices/concourse-pipeline-samples/tree/master/private-docker-registry] is already 2 years old, so maybe it's just outdated, but when I try to apply the inline-pipeline.yml I am getting an invalid configuration error

Output is below

`$ fly -t lite set-pipeline -p test-registry -c inline-pipeline.yml
groups:
  group main has been added:
    name: main
    jobs:
    - check-os-version
    - issue-ls-command

resources:
  resource concourse-pipeline-samples has been added:
    name: concourse-pipeline-samples
    type: git
    source:
      branch: master
      uri: https://github.com/pivotalservices/concourse-pipeline-samples.git

jobs:
  job check-os-version has been added:
    name: check-os-version
    public: true
    serial: true
    plan:
    - get: concourse-pipeline-samples
      trigger: true
    - task: check-image-os-version
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            insecure_registries:
            - 172.20.10.2:5000
            repository: 172.20.10.2:5000/ubuntu
            tag: latest
        run:
          path: cat
        inputs:
        - name: concourse-pipeline-samples
          path: ""
          optional: false

  job issue-ls-command has been added:
    name: issue-ls-command
    public: true
    serial: true
    plan:
    - get: concourse-pipeline-samples
      passed:
      - check-os-version
      trigger: true
    - task: issue-ls-command
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            insecure_registries:
            - 172.20.10.2:5000
            repository: 172.20.10.2:5000/ubuntu
            tag: latest
        run:
          path: ls
        inputs:
        - name: concourse-pipeline-samples
          path: ""
          optional: false

apply configuration? [yN]: y
error: invalid configuration:
unknown/extra keys:
  - jobs[0].plan[1].config.args
  - jobs[1].plan[1].config.args`

**Comment by lsilvapvt** [comment]
Thanks for reporting the problem. The `args` parameters were misaligned for that sample pipeline. 
I fixed it in commit https://github.com/pivotalservices/concourse-pipeline-samples/commit/1e4a4a2b427bbe1e92d299155d43b456aa3ba798. Regards.
